#!/usr/bin/env -S uv --quiet run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "psutil",
# ]
# ///

import psutil

print("{:5.1f}%".format(psutil.cpu_percent(interval=1)))
